# Generated by Django 2.2.11 on 2021-04-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
    ]
