# Generated by Django 2.2.11 on 2021-04-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_library', '0002_auto_20210430_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=100)),
                ('sclass', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
