# Generated by Django 2.2.11 on 2021-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_library', '0003_auto_20210430_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('bookID', models.IntegerField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
                ('publicationDate', models.DateField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
